sudo: required
services:
  - docker

before_install:
  - docker build -t af22domination/docker-react -f Dockerfile.dev .

script:
  - docker run af22domination/docker-react npm run test -- --coverage

